name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: KataCombinatorics -> Restore dependencies
      run: dotnet restore KataCombinatorics/KataCombinatorics.sln
    - name: KataCombinatorics -> Build
      run: dotnet build KataCombinatorics/KataCombinatorics.sln --no-restore
    - name: KataCombinatorics -> Test
      run: dotnet test KataCombinatorics/KataCombinatorics.sln --no-build --verbosity normal

    - name: KataFibonacci -> Restore dependencies
      run: dotnet restore KataFibonacci/KataFibonacci.sln
    - name: KataFibonacci -> Build
      run: dotnet build KataFibonacci/KataFibonacci.sln --no-restore
    - name: KataFibonacci -> Test
      run: dotnet test KataFibonacci/KataFibonacci.sln --no-build --verbosity normal

    - name: KataFizzBuzz -> Restore dependencies
      run: dotnet restore KataFizzBuzz/KataFizzBuzz.sln
    - name: KataFizzBuzz -> Build
      run: dotnet build KataFizzBuzz/KataFizzBuzz.sln --no-restore
    - name: KataFizzBuzz -> Test
      run: dotnet test KataFizzBuzz/KataFizzBuzz.sln --no-build --verbosity normal

    - name: KataGameOfLife -> Restore dependencies
      run: dotnet restore KataGameOfLife/KataGameOfLife.sln
    - name: KataGameOfLife -> Build
      run: dotnet build KataGameOfLife/KataGameOfLife.sln --no-restore
    - name: KataGameOfLife -> Test
      run: dotnet test KataGameOfLife/KataGameOfLife.sln --no-build --verbosity normal

    - name: KataGreatestCommonDivisor -> Restore dependencies
      run: dotnet restore KataGreatestCommonDivisor/KataGreatestCommonDivisor.sln
    - name: KataGreatestCommonDivisor -> Build
      run: dotnet build KataGreatestCommonDivisor/KataGreatestCommonDivisor.sln --no-restore
    - name: KataGreatestCommonDivisor -> Test
      run: dotnet test KataGreatestCommonDivisor/KataGreatestCommonDivisor.sln --no-build --verbosity normal

    - name: KataMoneyExchange -> Restore dependencies
      run: dotnet restore KataMoneyExchange/KataMoneyExchange.sln
    - name: KataMoneyExchange -> Build
      run: dotnet build KataMoneyExchange/KataMoneyExchange.sln --no-restore
    - name: KataMoneyExchange -> Test
      run: dotnet test KataMoneyExchange/KataMoneyExchange.sln --no-build --verbosity normal

    - name: KataPrimeFactors -> Restore dependencies
      run: dotnet restore KataPrimeFactors/KataPrimeFactors.sln
    - name: KataPrimeFactors -> Build
      run: dotnet build KataPrimeFactors/KataPrimeFactors.sln --no-restore
    - name: KataPrimeFactors -> Test
      run: dotnet test KataPrimeFactors/KataPrimeFactors.sln --no-build --verbosity normal

    - name: KataRomanNumerals -> Restore dependencies
      run: dotnet restore KataRomanNumerals/KataRomanNumerals.sln
    - name: KataRomanNumerals -> Build
      run: dotnet build KataRomanNumerals/KataRomanNumerals.sln --no-restore
    - name: KataRomanNumerals -> Test
      run: dotnet test KataRomanNumerals/KataRomanNumerals.sln --no-build --verbosity normal

