name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: KataCombinatorics -> Restore dependencies
      run: dotnet restore KataCombinatorics/KataCombinatorics.sln
    - name: KataCombinatorics -> Build
      run: dotnet build KataCombinatorics/KataCombinatorics.sln --no-restore
    - name: KataCombinatorics -> Test
      run: dotnet test KataCombinatorics/KataCombinatorics.sln --no-build --verbosity normal
    - name: KataFibonacci -> Restore dependencies
      run: dotnet restore KataFibonacci/KataFibonacci.sln
    - name: KataFibonacci -> Build
      run: dotnet build KataFibonacci/KataFibonacci.sln --no-restore
    - name: KataFibonacci -> Test
      run: dotnet test KataFibonacci/KataFibonacci.sln --no-build --verbosity normal
